import { describe, expect, it } from 'vitest';
import { CITIES, cityById } from './index';
import network from './network.json';

/**
 * network.json is generated by scripts/build-network.mjs, which reads the city
 * ids out of engine/cities.ts by parsing the file — it is a plain .mjs script
 * and engine/ is TypeScript, so it cannot import the real thing. These tests
 * are where the parse gets checked against the module it was parsed from. A
 * regex that drifts fails here rather than shipping a map whose bulbs light up
 * for the wrong city.
 */

const nodes = network.nodes;
const cityNodes = nodes.filter(n => n.kind === 'city');

describe('the built network', () => {
  it('carries one node per city, dot and junction in the traced graph', () => {
    // Read against the printed board, node by node, and corrected where the
    // trace and the board disagreed:
    //   d893 dot → junction, the Southern's fork out of Chattanooga
    //   d936 dot → junction, a bend on the NYC into Cleveland
    //   d872 removed, a crossing of the NYC and the B&O that the trace had
    //        made a shared node, letting a pawn change lines where the board
    //        prints no dot
    expect(nodes).toHaveLength(550);
    expect(cityNodes).toHaveLength(67);
    expect(nodes.filter(n => n.kind === 'dot')).toHaveLength(468);
    expect(nodes.filter(n => n.kind === 'junction')).toHaveLength(15);
    expect(new Set(nodes.map(n => n.id)).size).toBe(nodes.length);
  });

  it('agrees with the engine about which city each cityId is', () => {
    for (const node of cityNodes) {
      expect(cityById(node.cityId!).name).toBe(node.name);
    }
  });

  it('places every one of the engine\'s cities exactly once', () => {
    const placed = cityNodes.map(n => n.cityId).sort((a, b) => a! - b!);
    expect(placed).toEqual(CITIES.map(c => c.id));
  });

  it('gives only city nodes a name and an id', () => {
    for (const node of nodes.filter(n => n.kind !== 'city')) {
      expect(node).not.toHaveProperty('name');
      expect(node).not.toHaveProperty('cityId');
    }
  });

  it('puts every node somewhere on the map', () => {
    for (const node of nodes) {
      expect(Number.isFinite(node.lat), `${node.id} latitude`).toBe(true);
      expect(Number.isFinite(node.lon), `${node.id} longitude`).toBe(true);
      expect(node.lat, `${node.id} latitude`).toBeGreaterThan(22);
      expect(node.lat, `${node.id} latitude`).toBeLessThan(52);
      expect(node.lon, `${node.id} longitude`).toBeGreaterThan(-128);
      expect(node.lon, `${node.id} longitude`).toBeLessThan(-64);
    }
  });

  it('connects only nodes it actually has, and never one to itself', () => {
    const ids = new Set(nodes.map(n => n.id));
    for (const edge of network.edges) {
      expect(ids.has(edge.a), `edge from ${edge.a}`).toBe(true);
      expect(ids.has(edge.b), `edge to ${edge.b}`).toBe(true);
      expect(edge.a).not.toBe(edge.b);
      expect(edge.railroads.length).toBeGreaterThan(0);
    }
  });

  it('names no railroad on an edge that the network does not run', () => {
    // Edges carry railroad ids; network.railroads carries the records those
    // ids point at — id, full name, purchase cost and the colour the map draws
    // the line in.
    const known = new Set(network.railroads.map(r => r.id));
    expect(known.size).toBe(network.railroads.length);
    for (const edge of network.edges) {
      for (const line of edge.railroads) expect(known.has(line), line).toBe(true);
    }
  });

  it('runs every railroad it declares', () => {
    const used = new Set(network.edges.flatMap(e => e.railroads));
    expect([...network.railroads.map(r => r.id)].filter(id => !used.has(id))).toEqual([]);
    expect(network.railroads).toHaveLength(28);
  });

  it('keeps the two twin pairs apart rather than collapsing them', () => {
    // The board draws San Francisco/Oakland 5.5px apart and Minneapolis/
    // St. Paul 7.1px apart — far closer than any other pair, and the case most
    // likely to be flattened by a warp that smooths instead of interpolating.
    // They are also the board's only two $0 journeys, so a collapse here would
    // quietly merge the two destinations the payout table treats as distinct.
    const at = (name: string) => cityNodes.find(n => n.name === name)!;
    const km = (a: string, b: string) => {
      const [p, q] = [at(a), at(b)];
      return Math.hypot((p.lat - q.lat) * 111.32,
                        (p.lon - q.lon) * 111.32 * Math.cos((p.lat * Math.PI) / 180));
    };
    expect(km('San Francisco', 'Oakland')).toBeGreaterThan(5);
    expect(km('Minneapolis', 'St. Paul')).toBeGreaterThan(5);
  });
});
