#!/usr/bin/env node
// Extracts the lower-48 coastline from us-atlas into src/data/us-outline.json.
//
//   node scripts/build-outline.mjs [--write]
//
// The map draws the nation as one filled shape behind the network. us-atlas
// ships it as TopoJSON covering all fifty states plus Puerto Rico, which is
// the wrong shape (the board is the lower 48) and the wrong format (an arc
// index the app would have to decode on every mount).
//
// Doing it here instead means the app bundles a plain GeoJSON ring list and
// needs neither topojson-client nor us-atlas at runtime — they stay dev
// dependencies. Coordinates are rounded to 3 decimals, about 80m, which is
// far below one screen pixel at this scale and roughly halves the file.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import * as topojson from 'topojson-client';
import { geoCentroid } from 'd3-geo';

const write = process.argv.includes('--write');
const OUT = 'src/data/us-outline.json';

const require = createRequire(import.meta.url);
const topo = JSON.parse(readFileSync(require.resolve('us-atlas/nation-10m.json'), 'utf8'));

const feature = topojson.feature(topo, topo.objects.nation);
const nation = feature.type === 'FeatureCollection' ? feature.features[0] : feature;

// Alaska, Hawaii and Puerto Rico are all in this file and none is on the
// board. Selecting by where each ring's centroid falls keeps the lower 48
// without hard-coding which index they happen to occupy.
const BOX = { lon: [-127, -66], lat: [24, 50] };
const rings = nation.geometry.coordinates.filter(polygon => {
  const [lon, lat] = geoCentroid({ type: 'Polygon', coordinates: polygon });
  return lon > BOX.lon[0] && lon < BOX.lon[1] && lat > BOX.lat[0] && lat < BOX.lat[1];
});

if (!rings.length) {
  console.error('FAILED: no rings fell inside the lower-48 box — has us-atlas changed shape?');
  process.exit(1);
}

const round = n => Number(n.toFixed(3));
const coordinates = rings.map(poly => poly.map(ring => ring.map(([x, y]) => [round(x), round(y)])));
const points = coordinates.flat(2).length;

// The mainland is one big ring plus islands. If the biggest ring is not much
// bigger than the rest, the filter above has kept the wrong thing.
const sizes = coordinates.map(p => p[0].length).sort((a, b) => b - a);
if (sizes[0] < 1000) {
  console.error(`FAILED: largest ring has only ${sizes[0]} points — that is not the mainland.`);
  process.exit(1);
}

const out = {
  note: 'Generated by scripts/build-outline.mjs from us-atlas/nation-10m.json. '
      + 'Lower 48 only, WGS84 degrees, rounded to 3 decimals. Do not hand-edit.',
  type: 'Feature',
  properties: {},
  geometry: { type: 'MultiPolygon', coordinates }
};

console.log(`${rings.length} rings, ${points} points, largest ring ${sizes[0]} points`);
console.log(`${(JSON.stringify(out).length / 1024).toFixed(0)} KB`);

if (write) {
  mkdirSync('src/data', { recursive: true });
  writeFileSync(OUT, JSON.stringify(out) + '\n');
  console.log(`\nWrote ${OUT}`);
} else {
  console.log(`\nDry run — pass --write to emit ${OUT}`);
}
